### ISSUE TITLE
mpd error

### ISSUE THREAD

**Issue by teotwawki16** [shdown/luastatus#45]
When I run luastatus from the terminal, an error pops up:

`luastatus: (mpd@mpd.lua) warning: (candiate) connect: Connection refused`

But mpd works fine. I can control it my with bindings and whatnot. What does this error mean?

**Comment by shdown** [comment]
Well, the plugin calls the `getaddrinfo()` function that resolves a domain name into a *list* of IP addresses; then the plugin iterates over that list and tries to connect to any of them. This warning means that it failed to connect to the first one, and, since you say that it works fine, connects successfully to the second one.

This is a harmless warning, in other words.

**Comment by teotwawki16** [comment]
I guess I have no problems then. Thank you.
