### ISSUE TITLE
pulse plugin is disabled by default

### ISSUE THREAD

**Issue by lieux** [shdown/luastatus#55]
Every time I have to reinstall `luastatus`, I always have to open the `CMakeLists.txt` file and change the `pulse` plugin from `OFF` to `ON`. Is there a reason why this is disabled by default?

**Comment by shdown** [comment]
> Is there a reason why this is disabled by default?

A user typically wants to enable `alsa` xor `pulse`. Since PulseAudio is able to emulate alsa, but not vice versa, enabling `alsa` by default seems to be a good choice.

> I always have to open the CMakeLists.txt file and change the pulse plugin from OFF to ON.

Well, that’s not what you’re supposed to do.

Just run, e.g., `cmake -DBUILD_PLUGIN_PULSE=ON .` once in the repo directory. Then, whenever you want to rebuild luastatus, run `cmake . && make`. CMake stores your choices in the `CMakeCache.txt` file.

**Comment by lieux** [comment]
Old issue. Closing.
